### PR TITLE
fix switching to static address with lwip2

### LINKED ISSUE #5839: WiFi.config(fixedIP, fixedGateway, fixedNetmask) disconnects ESP on 2.5.0 (regression from 2.4.2)
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it. (no stack dump)
- [x] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12]
- Core Version:			[2.5.0]
- Development Env:		[Arduino IDE]
- Operating System:		[Slackware Linux]

### Settings in IDE

- Module:  			[Nodemcu]
- Flash Mode:			[unknown]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

When changing the IP address configuration with WiFi.config after connecting, 2.5.0 just releases the DHCP lease and returns the IP address but does not enable the fixed IP address. This works on 2.4.2.

After a disconnect->reconnect cycle, 2.5.0 activates the fixed IP address. (Side note: This seems shaky on 2.4.2 - does not work every time)

I checked the github web interface but could not make out any relevant changes to the ESP8266WiFi tree since 2.5.0, so I hope it's OK that I did not check latest-git.

If you need any more info, just go ahead and ask :)

Heiko

May be related to #5757 ?

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <ESP8266WiFi.h>

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  delay(100);

  IPAddress fixedIP(192, 168, 205, 225);
  IPAddress fixedGateway(192, 168, 205, 250);
  IPAddress fixedNetmask(255, 255, 255, 0);

  WiFi.config(0u, 0u, 0u);
  WiFi.begin("ssid", "psk");

  delay(10000);

  Serial.println("Switching to fixed IP - this is where 2.4.2 starts to respond to pings to .225, 2.5.0 does not");
  WiFi.config(fixedIP, fixedGateway, fixedNetmask);

  delay(5000);

  Serial.println("Reconnecting");
  WiFi.disconnect();
  delay(1000);
  WiFi.begin("ssid", "psk");
  Serial.println("Now 2.5.0 responds to pings to .225");
}

void loop() {
  // put your main code here, to run repeatedly:

}
```
### Debug Messages on 2.5.0
```
0x2d
csum 0x2d
v951aeffa
~ld
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 1
cnt 

connected with jmri-american, channel 1
dhcp client start...
ip:192.168.205.228,mask:255.255.255.0,gw:192.168.205.250
Switching to fixed IP - this is where 2.4.2 starts to respond to pings to .225, 2.5.0 does not
pm open,type:2 0
Reconnecting
state: 5 -> 0 (0)
rm 0
pm close 7
Now 2.5.0 responds to pings to .225
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 1
cnt 

connected with jmri-american, channel 1
ip:192.168.205.225,mask:255.255.255.0,gw:192.168.205.250
ip:192.168.205.225,mask:255.255.255.0,gw:192.168.205.250
pm open,type:2 0
```
### Debug Messages on 2.4.2
```
0x2d
csum 0x2d
vbb28d4a3
~ld
scandone
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 1
cnt 

connected with jmri-american, channel 1
dhcp client start...
ip:192.168.205.228,mask:255.255.255.0,gw:192.168.205.250
Switching to fixed IP - this is where 2.4.2 starts to respond to pings to .225, 2.5.0 does not
ip:192.168.205.225,mask:255.255.255.0,gw:192.168.205.250
pm open,type:2 0
Reconnecting
state: 5 -> 0 (0)
rm 0
pm close 7
Now 2.5.0 responds to pings to .225
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 1
cnt 

connected with jmri-american, channel 1
ip:192.168.205.225,mask:255.255.255.0,gw:192.168.205.250
ip:192.168.205.225,mask:255.255.255.0,gw:192.168.205.250
pm open,type:2 0
```

### LINKED ISSUE #6024: [Static IP] Code that previously worked no longer works
Hi,

Without setting a fixed address, the ESP8266 can get the IP address via DHCP, so the hello webserver example works normally. But if I add the static IP configuration, then the browser can not find the server (The serial monitor shows the static IP address correctly)

The code worked correctly until about November 2018 (it was the last time I tested it).

Were there any radical changes in the library?

Arduino IDE 1.8.9
ESP8266 2.5.0 (library installed using the Board Manager)
Windows 10 x64
NodeMCU Lolin V3

I will downgrade the library version to try to find a version that works.

Ref.: https://arduino-esp8266.readthedocs.io/en/2.5.0/esp8266wifi/station-class.html#config

Basic code:
```
WiFi.begin(ssid, password);
IPAddress ip(192,168,1,74);   
IPAddress gateway(192,168,1,1);   
IPAddress subnet(255,255,255,0);   
IPAddress dns(8,8,8,8); 
WiFi.config(ip, gateway, subnet, dns);
```

Thank you.

### PR DESCRIPTION
**Pull request by d-a-v**
For some reason, ip address is not propagated in a visible way for lwip2
when switching to static address (wifi.config()) *after* wifi.begin().

This patch calls lwip-v1.4's netif_set_addr() with the new ip address to set
all things up, just like it is done and right when wifi.begin() is called
after wifi.config().

Also tested when IPv6 is enabled.

fixes #5839
fixes #6024

### CODE REVIEW

File: libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp [hunk 1]
```diff
@@ -247,6 +247,13 @@ wl_status_t ESP8266WiFiSTAClass::begin() {
  * @param dns1       Static DNS server 1
  * @param dns2       Static DNS server 2
  */
+
+#if LWIP_VERSION_MAJOR != 1
+#undef netif_set_addr // need to call lwip-v1.4 netif_set_addr()
```
Comment (devyte) [inline libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp]: This is confusing to me. The define above means that lwip2 is in play, then this gets undef'd with a comment about using the lwip1.4 function, then a function is imported from extern.
Is an lwip1.4 function really being used? If so, is there now a dependency on both lwips?
Why the undef then import? is there a C-style name clash, so this is done to change the function?
