### PR TITLE
mDNS: protect MDNSResponder::queryService against misuse

### LINKED ISSUE #7215: Exception (28) on MDNSResponder::queryService
MDNSResponder::queryService crashes esp8266 with Exception (28) in case it is called before begin has been called

### PR DESCRIPTION
**Pull request by d-a-v**
fixes #7215

### CODE REVIEW

File: libraries/ESP8266mDNS/src/LEAmDNS.cpp [hunk 1]
```diff
@@ -767,6 +767,10 @@ uint32_t MDNSResponder::queryService(const char* p_pcService,
                                      const char* p_pcProtocol,
                                      const uint16_t p_u16Timeout /*= MDNS_QUERYSERVICES_WAIT_TIME*/)
 {
+    if (0 == m_pUDPContext)
```
Comment (devyte) [inline libraries/ESP8266mDNS/src/LEAmDNS.cpp:770]: Isn't this a ptr? check against nullptr?

Comment (d-a-v) [reply libraries/ESP8266mDNS/src/LEAmDNS.cpp:770]: Yes. For coherency I sticked to this file's style.
https://github.com/esp8266/Arduino/blob/e1789ddf0c73ff00cdca104e420ead5bc8bc016f/libraries/ESP8266mDNS/src/LEAmDNS.cpp#L101

I was afraid to modify too much for when LEAmDNS2 is coming to avoid merge complication.
