### PR TITLE
Check for WEP when setting authmode

### LINKED ISSUE #5359: Cannot connect to WEP network with WiFi.enableInsecureWEP()
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:				Wroom02
- Core Version:			74ca42f
- Development Env:		Platformio
- Operating System:		Windows

### Settings in IDE

- Module:  			Generic ESP8266 Module
- Flash Size: 		2MB
- lwip Variant:  v2 Lower Memory
- Reset Method:		nodemcu
- CPU Frequency:		160MHz

### Problem Description

An existing working setup has stopped being able to connect to a WEP network. If i change AP settings to WPA2 everything works as expected. This has been since upgrading the git core, unfortunately I cannot pinpoint the exact previous working git version.

I have tried before WiFi begin:
WiFi.enableInsecureWEP(true); 
WiFi.enableInsecureWEP(); 

WiFi error is 1  - Unreachable WiFi Network

All other device connect and work perfectly fine with the access point and the same credentials.

Here is a wifiscan output from the ESP, I have obscured the SSIDs, SSIDWPA2 is WPA2 encrytption and SSID WEP - WEP.

"SSID" : SSIDWEP,
"RSSI" : -30,
"encryption" : 5,
"BSSID" : 46:D9:E7:F3:35:B8,
"channel" : 6,
"isHidden" : false

"SSID" : SSIDWPA2,
"RSSI" : -30,
"encryption" : 4,
"BSSID" : 44:D9:E7:F3:35:B8,
"channel" : 6,
"isHidden" : false

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

I will create an MVCE if required, but my setup routine looks like this:

```
 void wifiSetup(){
    WiFi.hostname(config.deviceID);
    WiFi.enableInsecureWEP(); 
    WiFi.mode(WIFI_AP_STA);

    if(config.wifiSettings.fixedSettings){
        Serial.println(F("Applying fixed wifi settings"));
        IPAddress staticIP, gateway, subnet, dns1, dns2;
        if(staticIP.fromString(config.wifiSettings.ip)){
            if(gateway.fromString(config.wifiSettings.gateway)){
                if(subnet.fromString(config.wifiSettings.mask)){
                    if(dns1.fromString(config.wifiSettings.dns1)){
                        if(dns1.fromString(config.wifiSettings.dns2)){
                            WiFi.config(staticIP, gateway, subnet, dns1, dns2);
                        } else {
                            Serial.println(F("Failed DNS2 Address conversion"));
                            WiFi.config(staticIP, gateway, subnet, dns1);
                        }
                    }else{
                        Serial.println(F("Failed DNS1 Address conversion"));
                        WiFi.config(staticIP, gateway, subnet);
                    }        
                } else Serial.println(F("Failed Net Mask conversion"));  
            } else Serial.println(F("Failed Gateway Address conversion"));
        } else Serial.println(F("Failed IP Address conversion"));
    }
    WiFi.softAP(config.apSSID, config.apPassword);    
    if(strlen(config.wifiSettings.ssid) != 0){
        Serial.println(F("Begin WiFi"));
        Serial.print(F("Connecting to "));
        Serial.println(config.wifiSettings.ssid);
        WiFi.begin(config.wifiSettings.ssid, config.wifiSettings.password);
    }
}
```
### Debug Messages

```
mode : sta(84:f3:eb:46:dd:c3) + softAP(86:f3:eb:46:dd:c3)
add if0
Begin WiFi
Connecting to SSIDWEP
scandone
no SSIDWEP found, reconnect after 1s
reconnect
scandone
no SSIDWEP found, reconnect after 1s
reconnect
scandone
no SSIDWEP found, reconnect after 1s
reconnect
scandone
no SSIDWEP found, reconnect after 1s
reconnect
scandone
no SSIDWEP found, reconnect after 1s
reconnect
scandone
no SSIDWEP found, reconnect after 1s
reconnect
WiFi Failure - 1
Unreachable WiFi Network
scandone
del if0
mode : softAP(86:f3:eb:46:dd:c3)
```

### PR DESCRIPTION
**Pull request by dav1901**
Fix #5359.

### CODE REVIEW

File: libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp [hunk 1]
```diff
@@ -121,7 +121,9 @@ wl_status_t ESP8266WiFiSTAClass::begin(const char* ssid, const char *passphrase,
     conf.threshold.authmode = AUTH_OPEN;
 
     if(passphrase) {
-        conf.threshold.authmode = AUTH_WPA_PSK;
+        if (!_useInsecureWEP) {
```
Comment (devyte) [inline libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp]: This is missing the else, and un-reverse the logic: Something like this:
`conf.threshold.authmode = _useInsecureWEP ?  AUTH_WEP : AUTH_WPA`;

The reason why the else is needed is to avoid having the ESP bounce off the intended AP and connect to an open AP. In other words, if a pass is provided, avoid connecting to any open AP.

Comment (dav1901) [reply libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp]: done
