### PR TITLE
Stream::send()

### LINKED ISSUE #6907: Stream File Problems 2.6.2
##Platform

- Hardware:                             ESP-12
- Core Version:			2.6.2
- Development Env:		Arduino
- Operating System:		Windows

### Settings in IDE
image

### Problem Description

**Webserver stream problems:**
```cpp
bool ServerFileReadFS(String Path) {
  Waiting();
  if (Path.endsWith(F("/"))) Path += F("home.htm");
  String contentType = ServerContentType(Path);
  String PathWithGz = Path + F(".gz");
  if (FilesFSExists(PathWithGz))  Path += F(".gz");
  if (FilesFSOpen(Path)) {
    DebugSerial.println(String(F("ServerFileReadFS: Load ")) + (Path));
    if (server.streamFile(FilesFS, contentType) == FilesFS.size()) {
      FilesFSClose();
      return 1;
    } //else DebugSerial.println(String(F("ServerLoadFile: FS Error stream File ")) + (Path));
  } //else DebugSerial.println(String(F("ServerLoadFile: FS File not Exists ")) + (Path));
  FilesFSClose();
  return 0;
}
```

### Debug Messages

```
ServerFileReadFS: Load /home.htm.gz

User exception (panic/abort/assert)
Panic src/include/DataSource.h:93 const uint8_t* BufferedStreamDataSource<TStream>::get_buffer(size_t) [with TStream = Stream; uint8_t = unsigned char; size_t: Assertion 'cb == stream_rem' failed.

>>>stack>>>

ctx: cont
sp: 3ffffd30 end: 3fffffc0 offset: 0000
3ffffd30:  3fff6364 0000036f 3fff300c 40245e0d  
3ffffd40:  000000fe 00000000 00000000 00000000  
3ffffd50:  00000000 00000000 00000000 4028f974  
3ffffd60:  3fff1768 00000000 3fff4b0c 0000036f  
3ffffd70:  0000036f 00000000 3fff4b0c 402427c6  
3ffffd80:  00000000 00000000 4bc6a7f0 4024280e  
3ffffd90:  3fff5b5c 00000000 3fff4b0c 40234f6a  
3ffffda0:  00000000 3fff02c8 00000020 0000036f  
3ffffdb0:  00000000 0000036f 3fff5b5c 40235145  
3ffffdc0:  3fff5b5c 0000086a 0000001c 0000086a  
3ffffdd0:  00000001 3fff0bfc 3fff5b5c 40235206  
3ffffde0:  3fff5b5c 3fff0bfc 00000000 40235740  
3ffffdf0:  80fffe88 3ffffe10 3fff0bfc 0000086a  
3ffffe00:  3ffffe88 3fff02c8 3fff0bfc 4022f5e1  
3ffffe10:  3fff4b00 000c000f 80fffe4c 40240a51  
3ffffe20:  3fff2134 3ffffeb0 3ffffeb0 3fff1728  
3ffffe30:  00000000 00000001 3fff0bfc 4022f916  
3ffffe40:  3fff5f00 0023002f 80ff006d 3fff4b00  
3ffffe50:  0017001f 8028d524 3fff4b00 000c000f  
3ffffe60:  80000000 3fff2100 000c000f 80240c30  
3ffffe70:  3fff2100 000c000f 80ff006d 3fff4aec  
3ffffe80:  000c000f 00ff0308 74786574 6d74682f  
3ffffe90:  89ff006c 59524f54 80ff002f 40240e14  
3ffffea0:  00000000 3fff0308 3ffffed0 4022fab2  
3ffffeb0:  3fff2134 000c000f 09fe006d 4023f648  
3ffffec0:  00000000 3fff0308 3fff02c8 4022fc7a  
3ffffed0:  0000002f 00000019 81ff15f8 4023fcc8  
3ffffee0:  00000000 3fff0308 3fff02c8 401000e1  
3ffffef0:  00544500 3fff0308 3fff02c8 40230b3a  
3fffff00:  00000000 80000000 4bc6a700 00000000  
3fffff10:  8023f63c 3fff6000 0000007f 80005054  
3fffff20:  3fff02ec 3fff0308 00000001 40201974  
3fffff30:  00794235 0000000a 3fff15f8 4023fcc8  
3fffff40:  3fffdad0 00000000 3fff02c8 3fff1728  
3fffff50:  00000001 3fff02ec 3fff02c8 40231f74  
3fffff60:  4024d0b0 00000000 00001388 4022e934  
3fffff70:  00000000 3fff5b5c 80ff16e8 40203248  
3fffff80:  3fffdad0 00000000 3fff16e8 40232038  
3fffff90:  3fffdad0 00000000 3fff16e8 40232063  
3fffffa0:  feefeffe feefeffe feefeffe 402421a0  
3fffffb0:  feefeffe feefeffe 3ffe97a4 40101665  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

```
```
Decoding 28 results
0x40245e0d: spiffs_hydro_read at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\cores\esp8266\spiffs/spiffs_hydrogen.cpp line 418
:  (inlined by) SPIFFS_read at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\cores\esp8266\spiffs/spiffs_hydrogen.cpp line 429
0x4028f974: chip_v6_unset_chanfreq at ?? line ?
0x402427c6: raise_exception at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\cores\esp8266/core_esp8266_postmortem.cpp line 245
0x4024280e: __assert_func at ?? line ?
0x40234f6a: BufferedStreamDataSource ::get_buffer(unsigned int) at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/include/DataSource.h line 95
0x40235145: ClientContext::_write_some() at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/include/ClientContext.h line 495
0x40235206: ClientContext::_write_from_source(DataSource*) at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/include/ClientContext.h line 450
0x40235740: WiFiClient::write(Stream&) at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/include/ClientContext.h line 372
:  (inlined by) WiFiClient::write(Stream&) at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/WiFiClient.cpp line 242
0x4022f5e1: unsigned int esp8266webserver::ESP8266WebServerTemplate ::streamFile (fs::File&, String const&) at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WebServer\src/ESP8266WebServer.h line 157 (discriminator 1)
0x40240a51: String::invalidate() at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\cores\esp8266/WString.cpp line 140
0x4022f916: ServerFileReadFS(String) at C:\Users\Laercio Mendon�a\AppData\Local\Temp\arduino_build_763520\sketch/Server.h line 121
0x40240e14: String::operator=(String const&) at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\cores\esp8266/WString.cpp line 262
0x4022fab2: ServerLoadFile(String) at C:\Users\Laercio Mendon�a\AppData\Local\Temp\arduino_build_763520\sketch/Server.h line 134
0x4023f648: HardwareSerial::write(unsigned char const*, unsigned int) at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\cores\esp8266/HardwareSerial.h line 165
0x4022fc7a: operator() at C:\Users\Laercio Mendon�a\AppData\Local\Temp\arduino_build_763520\sketch/Server.h line 402
:  (inlined by) _M_invoke at d:\setup\programas\desenvolvimento\arduinocoretest\portable\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\4.8.2/functional line 2071
0x4023fcc8: Print::println() at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\cores\esp8266/Print.cpp line 178
0x401000e1: std::function ::operator()() const at d:\setup\programas\desenvolvimento\arduinocoretest\portable\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\4.8.2/functional line 2465
0x40230b3a: esp8266webserver::ESP8266WebServerTemplate ::_handleRequest() at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h line 673
0x40201974: esp8266webserver::FunctionRequestHandler ::canHandle(HTTPMethod, String) at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WebServer\src/detail/RequestHandlersImpl.h line 23
0x4023fcc8: Print::println() at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\cores\esp8266/Print.cpp line 178
0x40231f74: esp8266webserver::ESP8266WebServerTemplate ::handleClient() at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h line 335
0x4024d0b0: spiffs_cache_page_get_by_fd at ?? line ?
0x4022e934: SerialDebugMonitor() at C:\Users\Laercio Mendon�a\AppData\Local\Temp\arduino_build_763520\sketch/Serial.h line 20 (discriminator 1)
0x40203248: RTCMonitor() at C:\Users\Laercio Mendon�a\AppData\Local\Temp\arduino_build_763520\sketch/RTC.h line 227
0x40232038: Waiting at C:\Users\Laercio Mendon�a\AppData\Local\Temp\arduino_build_763520\sketch/Server.h line 410
:  (inlined by) ServerMonitor() at C:\Users\Laercio Mendon�a\AppData\Local\Temp\arduino_build_763520\sketch/Server.h line 411
0x40232063: loop at D:\Save\Aquarino\Projects\Aquarino-ControllerBeta/Aquarino-ControllerBeta.ino line 90
0x402421a0: loop_wrapper() at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\cores\esp8266/core_esp8266_main.cpp line 180
0x40101665: cont_wrapper at D:\SETUP\Programas\Desenvolvimento\ArduinoCoreTest\portable\packages\esp8266\hardware\esp8266\2.6.2\cores\esp8266/cont.S line 81
```

### PR DESCRIPTION
**Pull request by d-a-v**
*edit*:

fixes #6907 (datasource is replaced by stream) ([comment](https://github.com/esp8266/Arduino/issues/6907#issuecomment-633109307))

*edit*:

References to "String is Stream" are removed:
An helper class `S2Stream myStringVarNowIsAStream(myStringVar)` has been added to make an already existing `String` into a `Stream`, and `StreamString` derives from it.

*edit*:

- \+ [device test](https://github.com/d-a-v/Arduino/blob/streamto/tests/device/test_sw_StreamString/test_sw_StreamString.ino) combined with [an example](https://github.com/d-a-v/Arduino/blob/streamto/libraries/esp8266/examples/StreamString/StreamString.ino)

- \+ [documentation](https://github.com/d-a-v/Arduino/blob/streamto/doc/reference.rst#streams)

*edit*:

- `WiFiEcho` server sketch example, with provided python echo client:

| code | BW (Kibits/s) | min. free stack (Bytes) |
| ----- | ----- | ----- |
| [byte by byte](https://github.com/d-a-v/Arduino/blob/streamto/libraries/ESP8266WiFi/examples/WiFiEcho/WiFiEcho.ino#L98L103) | 539 | 2864 |
| [512 bytes stack buffer](https://github.com/d-a-v/Arduino/blob/streamto/libraries/ESP8266WiFi/examples/WiFiEcho/WiFiEcho.ino#L108L119) | 4295 | 2212 |
| [Stream::to()](https://github.com/d-a-v/Arduino/blob/streamto/libraries/ESP8266WiFi/examples/WiFiEcho/WiFiEcho.ino#L127) | 4980 | 2576  |

*(these results are environment-dependent and have been made under the same conditions)*

- [Optional virtual peekBuffer API to allow direct access to data](https://github.com/d-a-v/Arduino/blob/bf9ad754ea0ab57133ac1147fce4d5d6bd2c95f4/cores/esp8266/Stream.h#L115L139) (internal Stream API, currently implemented by HardwareSerial and WiFiClient/Secure)

- [API addition is summarized here](https://github.com/d-a-v/Arduino/blob/bf9ad754ea0ab57133ac1147fce4d5d6bd2c95f4/cores/esp8266/Stream.h#L141L199) (user facing API)

Additional notes:
  - flash strings or char arrays can be [directly/generically streamed](https://github.com/d-a-v/Arduino/blob/f85ddbb30ca485133bd67204064f72e2a0d6de64/cores/esp8266/StreamDev.h#L89L92)
- `ClientContext`: `DataSource` is removed and replaced by `Stream::` offering the same services: from Stream, from in-ram data, from in-flash data). That's also an additional reduction of allocation frequency.

Cost:

* `BasicHttpClient.ino:` (less than 1KB in flash)

with master:
```
IROM   : 259112          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 27080   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1148  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 1212  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 26408 )         - zeroed variables      (global, static) in RAM/HEAP 
```

w/ `Stream::to` PR:
```
IROM   : 260056          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 26904   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1148  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 1220  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 26408 )         - zeroed variables      (global, static) in RAM/HEAP 
```
~~Ref: https://github.com/plerup/espsoftwareserial/pull/171 replaced by~~ #7840
~~Ref: https://github.com/bblanchon/ArduinoJson/pull/1341~~

*OP*: (*fixed*)

This pull request aims at simplifying transfers between sources (`Stream`, `String`) and destinations (`Print`, `String`) in a single function in a single location.

This kind of transfer is indeed reimplemented everytime it is needed making the esp8266 arduino core (or any code using `Stream`) hard to optimize or maintain.  There are no general functionality difference between any of these transfers.

The proposed implementation is in the form of "Stream::to*(Print)".  This function relies on Arduino virtual Stream and Print API.  The Arduino Stream API is historically limited so such transfers require the use of an intermediary buffer, implying two copies.  This pull request also proposes an extension to the Stream API which allows to reduce the number of copies and avoid the use of such buffer.  It is called in the following the "`peekBuffer` extension".

The `peekBuffer` extension is not a breaking change.  It is by default not available (ie disabled in `Stream::`) and can be enabled by any stream class extender (`bool Stream::peekBufferAPI()`).

This pull request enables the `Stream`'s `peekBuffer` API in `WiFiClient::`, `WiFiClientSecureBearSSL::`, `HardwareSerial::` and `StreamString::`.  The latter ***is optionally*** merged with `String::` and this can be seen as a breaking change in some particular cases where libraries like ArduinoJson has overloads for `Stream::` and `String::`.

At the time of writing, `Stream`'s `peekBuffer` API has yet to be implemented in the filesystem classes (`SDFat`, `LittleFS`, `SPIFFS`).
Implementing it in external libraries such as `EspSoftwareSerial` should not induce changes in binary size or API compatibility with other cores.

Lots of places in the esp8266 arduino core would benefit from `Stream::to()`.  This pull request proposes changes to `ESP8266HTTPClient` (it allowed to remove some big chunks of code including the interesting `HTTPClient::writeToStreamDataBlock()`).  This change is (partly) validated by the device test `test_sw_http_client` (http, https) that can also be run-tested on host.

Some parts of `ESP8266WebServer` have been updated to use `Stream::to()`.  Some examples too (Telnet2Serial, serial tests, ...) deserves the same changes.
A new example called `WiFiEcho` has been added to demonstrate the simplicity of the API.

About the functions `Stream::to*()`, they allow to
- transfer with no timeout all immediately available data from a `Stream` to a `Print`
- or, with a timeout, a specific amount of bytes
- or, with a timeout, bytes until a char delimiter.

The timeout used is by default the stream's one and can be changed in arguments.
The `peekBuffer` API is used when available and avoids the use of an intermediary buffer with a twofold effect: speed and absence of any kind of stack/heap allocation.
When `peekBuffer` is not available, `Stream::to()` does the job using the legacy way.

### CODE REVIEW

File: cores/esp8266/Print.cpp [hunk 1]
```diff
@@ -312,3 +304,8 @@ size_t Print::printFloat(double number, uint8_t digits) {
 
     return n;
 }
+
+int Print::availableForWrite() {
+    IAMSLOW();
+    return 1;
```
Comment (jandrassy) [inline cores/esp8266/Print.cpp]: according to comment in Arduino Print.h the default availableForWrite should return 0

> // default to zero, meaning "a single write may block"
    // should be overriden by subclasses with buffering
    virtual int availableForWrite() { return 0; }

**Comment by jandrassy** [comment]
something to consider: the compiler can't optimize away unused virtual functions of classes used. and this PR adds a lot of them

File: cores/esp8266/Print.cpp (hunk 1 above)
Comment (d-a-v) [reply cores/esp8266/Print.cpp]: done

**Comment by bblanchon** [comment]
In the name of cross-platform library developers: stop this nonsense!

Changing the interfaces of core classes, like `Stream` and `String`, will break the compatibility with other platforms.

Here are three examples that I could quickly find in this mastodon; there are probably more:

* deriving `String` from `Stream`, will break function overloads that support both, by making the call ambiguous.  
  (also, it introduces a circular dependency that will probably break some derived classes)
* changing the signature of a virtual function will break derived classes that override this method.
* changing the return type from `size_t` to `int` (why?) will produce a compiler warning on existing code and could potentially overflow.

True, the core classes were not really well designed, but we have to cope with them because that's the core itself that makes all Arduino-compatible platforms work alike.

Moreover, if deriving `String` from `Stream` was such a good idea, we can wonder why the STL (which, despite its few defects, is still a very well-designed library) doesn't do it!

**Comment by TD-er** [comment]
[...]

> Moreover, if deriving `String` from `Stream` was such a good idea, we can wonder why the STL (which, despite its few defects, is still a very well-designed library) doesn't do it!

Well there is the [std::stringstream container](http://www.cplusplus.com/reference/sstream/stringstream/stringstream/)

**Comment by bblanchon** [comment]
@TD-er, you're helping my point. In the same way, Arduino has [StringStream](https://github.com/bblanchon/ArduinoStreamUtils#writing-to-a-string).

**Comment by TD-er** [comment]
Not saying I disagree with you, only my opinion isn't that strong in here.
So if all other libraries use a separate object for string and for stringstream, then they probably have a good point there.
About the need to keep compliant with the Arduino libraries, I'm not that strong in my opinion.
If the "original" core is flawed in some way, I tend to believe it should not be continued to be done for the sake of compatibility.

Sure there is some hurdle if it breaks code, especially given the fact a lot of Arduino users are not that experienced in coding.
But I don't agree on forcing things to remain compatible to flawed by design code.
I don't know how flawed by design the code is that's going to be broken here, so therefore my opinion isn't well formed in this case.

Changing a return type from `size_t` to `int` could be chosen to add the option for negative return values (e.g. error states), which is also quite common in other Arduino code.  (and not always used consistently)
As I don't know (yet) what specific code this is about, I can't tell if that's likely to run into issues.
If it is related to the number of bytes, then it is unlikely it will affect Arduino code, unless it is some counter of bytes sent over an interface.
As counter argument, the size of `int` (4 bytes) is likely to be a bit more constant compared to `size_t` as the last one always has room to store a pointer.

Maybe you can give some examples in the code of this PR where the return type has changed in such a way?
Also about the virtual function signature change you mention?

**Comment by d-a-v** [comment]
@bblanchon I have respected your decision to not add a very simple and experimental, portable and harmless define, compatible with all other arduino cores, to your library.

`String::` derivated from `Stream::` is only an optional subset of the changes proposed in this pull request. It is seriously threatened by your prompt refusal. That it is harmful has yet to be proven. I have so far encountered issues only with your library (that is an excellent and very optimized one, but you know that already).

The change of the return type from `size_t` to `int` is ***not*** an Arduino API change, and is ***because*** of the `Client::` Arduino API. The `::read(buffer)` is imported and should have been defined in `Stream::` in the first place. Unfortunately, implementers for other classes derivating from `Stream::` decided to use a `size_t`. This PR aims at changing that because of inheritance, for coherency, and also for data transfer optimization.

The core of this PR is twofold:
- the `Stream::to*()` API, that is an API addition, which does not interfere with Arduino, and which does not strictly need to be optimized, that allows to replace often badly coded chunks of code, repeated tons of times here and there, by a single valid "core" call which needs fixes and optimizations in only one place,
- its optimization, through the "`peekBuffer`" API that is internal to `Stream::` and derivatives through the *virtual* `Stream::` API, and which does not interfere with Arduino.
This optimization allows to peek a buffer from where it already is, instead of having to `Stream::read()` (= copy) its data to temporary stack or heap buffers.

Let me answer to your points:
> deriving String from Stream, will break function overloads that support both, by making the call ambiguous. (also, it introduces a circular dependency that will probably break some derived classes)

I saw that only on your library, and like I said, the proposed change [is harmless](https://github.com/bblanchon/ArduinoJson/pull/1341/files) regarding your library with the other cores.
Very low number of libraries would have such an issue. You are making extensive use of template to get the best of all possible optimizations, and that is what makes your library great. Other libraries are not that much cooked. This is the reason why I believe that kind of change will not have much consequences. 

> changing the signature of a virtual function will break derived classes that override this method.

As stated above, there is no Arduino API change in this PR (other than the optional derivation of`Stream` in `String` which is not the essence of this PR).

> changing the return type from size_t to int (why?) will produce a compiler warning on existing code and could potentially overflow.

Reason is explained, and again, `int` ***is*** the type adopted by official Arduino in `Client::`. This PR imports it to `Stream::`.

> Moreover, if deriving String from Stream was such a good idea, we can wonder why the STL (which, despite its few defects, is still a very well-designed library) doesn't do it!

Why would we have an Arduino library if `std::` could be used everywhere ?

I'm open to understand why `String` cannot really be derived from `Stream`. It is just natural to have it like this. It simplifies coding, reduce flash footprint while being generic.

It's not the first time I'm trying to address the Arduino API caveats. I already paid it once in this repo by having to revert a quite large PR back. As maintainers, I, we do whatever it costs to preserve compatibility with Arduino.
Apart from the String issue I can see no non-sense, or please be more accurate.

I will hate to go back and reconsider `StringStream::` because that one is really a non-sense. I envy your place where you are the author of your library and where nobody can stand through your journey neither prevent you from changing everything in the API in the name of memory/speed optimization (those in the back of the room who are still on ArduinoJson 5.x raise hand please) :)

**Comment by earlephilhower** [comment]
Does this change anything related to the StreamString O(n^2) issue discussed in #4584 ?

**Comment by d-a-v** [comment]
> Does this change anything related to the StreamString O(n^2) issue discussed in #4584 ?

I had forgotten about it, sorry @Adam5Wu.
Changes are essentially the same:
- #4584 implements a read by block (`readBytes`) and makes the string not consumed
  which is a breaking change.
- This PR does the same (`read(void)`, `read(buffer)`, `readBytes()`, and `peekBuffer()`)
  - by default in consumed mode (legacy, not like #4584)
    - `read(void)` is still o(n²)
    - reading by block is possible, not o(n²)
  - can be set in non-consume mode (using `::reset()`, same function as in #4584)
    - `read(void)` is o(n)

I'm not against a breaking change to set non-consume mode by default, like in #4584.

**Comment by jandrassy** [comment]
I would not use Print::writeError in Stream

**Comment by d-a-v** [comment]
> something to consider: the compiler can't optimize away unused virtual functions of classes used. and this PR adds a lot of them

That was temporary, because of the `::read(buffer)` return type.
There are however more virtual functions than in master, the impact is showed in updated OP.

> I would not use `Print::writeError` in Stream's reading function

This member is left untouched when not using `Stream::to*()` functions.
Arduino API is left untouched.
Beside, any value different from 0 (`=STREAMTO_SUCCESS`) can be considered to be an error regarding the whole stream.
I have been reluctant to add another member "readError" and preferred to factorize what is already here. Users need to know that the stream I/O has an error. Be it an input or an output error (0 or <>0) makes little difference on what action to be taken. Still, details are there by reading the actual value of this member.

Regarding these considerations, can you please clarify your concerns ?

**Comment by jandrassy** [comment]
> Regarding these considerations, can you please clarify your concerns ?

Arduino Print+Stream has 7 virtual functions.
esp8266 has already additional virtual functions
2 readBytes
readString

the peek buffer API adds 5 virtual functions. 
other new virtual functions for all classes derived from stream are 
streamSize
virtual bool outputTimeoutPossible
virtual int read (uint8_t* buffer, size_t len);

this are small function but they will be always in bin. used or not. including override versions in all classes used in the sketch.

about writeError
```
client.toAll(&file);
if (client.getWriteError() || file.getWriteError()) {
...
}
```
doesn't seem right

**Comment by d-a-v** [comment]
> esp8266 has already additional virtual functions (why?)
2 `readBytes`
`readString`

I don't know. This is history on this repository. One can find the commits where they were added.

> the peek buffer API adds 5 virtual functions.
other new virtual functions for all classes derived from stream are
`streamSize`
`virtual bool outputTimeoutPossible`
`virtual int read (uint8_t* buffer, size_t len);`
These are small function but they will be always in bin. used or not. including override versions in all classes used in the sketch.

`read()` itself was already in the derived classes. I just made it virtual so I can use it for faster operations. `read()` is similar to `readBytes()` without timeout.

I showed in OP the flash size increase in a typical example. I can show more if needed.
Arduino API is virtual. The "peekBuffer" optimisation is transparent, implemented once for all classes and derivatives and allowed thanks to this virtual API. Like you noticed, the functions are small and overhead is quite limited. A templated implementation would have resulted in a distinct recompilation for every class used.

About `getWriteError()`, the proposed API is different:
```
client.toAll(&file);
if (client.getLastTo() != STREAMTO_SUCCESS) {
            // possible errors:
            //STREAMTO_TIMED_OUT,   read has timed out
            //STREAMTO_READ_ERROR,  reported by stream
            //STREAMTO_WRITE_ERROR, reported by  print
            //STREAMTO_SHORT,       could not write all required data (but reported as possible by availableForWrite)
}
```

> or did you consider doing the copying only with utility functions like StreamUtil::copyAll(&client, &file);?

I don't know what you are referring to. I have not found such method in the StreamUtils library.
`Stream::to*(printInstance)` methods will move all or parts of the source (Stream) to the `printInstance` (Print) destination, possibly by using the peekBuffer API to speed up transfers.

> it is usual that destination is left or first parmeter as in assignment operator. what is the reason to have this functions in Stream and not in Print?

I will be able to answer when I will be explained the reason why `Stream::` derives from `Print::`. In the meantime, the highest level class where both read and write functions are accessible is `Stream::`.

**Comment by jandrassy** [comment]
> > it is usual that destination is left or first parmeter as in assignment operator. what is the reason to have this functions in Stream and not in Print?
> 
> I will be able to answer when I will be explained the reason why `Stream::` derives from `Print::`. In the meantime, the highest level class where both read and write functions are accessible is `Stream::`.

because read-only is a sub set of read and write?
why do you need read functions for the destination?

I was thinking about some new StreamUtil class or namespace in esp8266 core. not the StreamUtils library.

Inspired by this idea of copying functions I added [simple functions](https://github.com/jandrassy/StreamLib/blob/0a548096e17db355b7228955c1a541df2ac73cfe/src/PrintPlus.cpp#L92) to my StreamLib library. The functions are in the target Print, not in destination Stream.

**Comment by d-a-v** [comment]
The method has to be either `Reader::to(Writer)` or `Writer::from(Reader)`.
I chose the first, and it is `Stream::to(Print)` in Arduino world.
Indeed in this use case, `Print` is target, `Stream` is input.
...If I understood the question.
 
Sorry from the `StreamUtil`(`s`) names confusion.
(; Your class speed could be powered up and be using less intermediary-stack-buffer when using the peekbuffer API. ;)

File: cores/esp8266/FS.h [hunk 2]
```diff
@@ -67,13 +67,14 @@ class File : public Stream
...
     }
-    size_t read(uint8_t* buf, size_t size);
+    int read(uint8_t* buf, size_t size) override;
     bool seek(uint32_t pos, SeekMode mode);
     bool seek(uint32_t pos) {
         return seek(pos, SeekSet);
     }
     size_t position() const;
     size_t size() const;
+    virtual ssize_t streamSize() override { return size() - position(); }
```
Comment (earlephilhower) [inline cores/esp8266/FS.h:77]: While technically I can see it, what would a negative `streamSize()` mean, anyway???

File: cores/esp8266/HardwareSerial.h [hunk 3]
```diff
@@ -135,16 +135,45 @@ class HardwareSerial: public Stream
...
+    {
+        return uart_peek_available(_uart);
+    }
+
+    // consume bytes after use (see peekBuffer)
+    void peekConsume (size_t consume) override
+    {
+        return uart_peek_consume(_uart, consume);
+    }
+
```
Comment (earlephilhower) [inline cores/esp8266/HardwareSerial.h:162]: @devyte, is this a spot for multiple inheritance?  Add a new `PeekBuffer` interface class?  Sorry if I'm getting all JAVA on you...

That said, I'm fine with this way, too.

File: cores/esp8266/HardwareSerial.h [hunk 4]
```diff
@@ -135,16 +135,45 @@ class HardwareSerial: public Stream
...
+    // return a pointer to available data buffer (size = available())
+    // semantic forbids any kind of read() before calling peekConsume()
+    const char* peekBuffer () override
+    {
+        return uart_peek_buffer(_uart);
+    }
+
+    // return number of byte accessible by peekBuffer()
+    size_t availableForPeek () override
```
Comment (earlephilhower) [inline cores/esp8266/HardwareSerial.h:152]: This is pure style, so ignore as you want, but having all the peek APi start with `peek` seems like a good thing, so I'd really use `peekAvailable()` as the method name in the base class...

File: cores/esp8266/StreamDev.cpp [hunk 5]
```diff
@@ -0,0 +1,333 @@
...
+                if (readUntilChar >= 0)
+                {
+                    const char* last = (const char*)memchr(directbuf, readUntilChar, w);
+                    if (last)
+                    {
+                        w = std::min((size_t)(last - directbuf), w);
+                        foundChar = true;
+                    }
+                }
+                if (w && ((w = to->write(directbuf, w))))
```
Comment (earlephilhower) [inline cores/esp8266/StreamDev.cpp:99]: So here we take the raw buffer from the source and pass it to the dest to write directly.  I'm wondering if there are cases where the source could be in IRAM/PMEM and the destination write goes boom?  Maybe I'm overthinking.  For String it's always byte-addressible RAM, same for File and Client....

File: cores/esp8266/StreamDev.cpp [hunk 6]
```diff
@@ -0,0 +1,333 @@
...
+            {
+                w = std::min(w, maxLen - written);
+            }
+            if (w)
+            {
+                const char* directbuf = peekBuffer();
+                bool foundChar = false;
+                if (readUntilChar >= 0)
+                {
+                    const char* last = (const char*)memchr(directbuf, readUntilChar, w);
```
Comment (earlephilhower) [inline cores/esp8266/StreamDev.cpp:92]: Do we need memchr_P?  Same as other question, does the peekBuffer API enforce byte-addressible RAM only?

File: cores/esp8266/StreamDev.h [hunk 7]
```diff
@@ -0,0 +1,255 @@
...
+class StreamPtr: public StreamNull
+{
+protected:
+    const char* _buffer;
+    size_t _size;
+    bool _in_flash;
+    size_t _peekPointer = 0;
+
+public:
+    StreamPtr(const String& string): _buffer(string.c_str()), _size(string.length()), _in_flash(false) { }
```
Comment (earlephilhower) [inline cores/esp8266/StreamDev.h:163]: Can you remove the `in_flash` param completely and just check the actual address is <0x4000_0000?  One less thing for users to get wrong.

File: cores/esp8266/debug.cpp [hunk 8]
```diff
@@ -22,16 +22,23 @@
 #include "debug.h"
 #include "osapi.h"
 
+#ifdef DEBUG_ESP_CORE
+void iamslow (const char* what)
```
Comment (earlephilhower) [inline cores/esp8266/debug.cpp:26]: I think you moved the fcns here to `extern "C"` with a prior PR?  Same here?

Also, just for sanity, maybe `__IAMSLOW()` or something (i.e. underscores to indicate internal use)?  Pedantic, not a big deal.

File: doc/reference.rst [hunk 9]
```diff
@@ -323,3 +323,193 @@ C++
     This assures correct behavior, including handling of all subobjects, which guarantees stability.
 
   History: `#6269 <https://github.com/esp8266/Arduino/issues/6269>`__ `#6309 <https://github.com/esp8266/Arduino/pull/6309>`__ `#6312 <https://github.com/esp8266/Arduino/pull/6312>`__
+
```
Comment (earlephilhower) [inline doc/reference.rst:326]: Nice documentation add!  👍

File: doc/reference.rst [hunk 10]
```diff
@@ -323,3 +323,193 @@ C++
...
+  Classes derived from ``Stream::`` also usually introduce the ``read(buffer,
+  len)`` method, which is similar to ``readBytes(buffer, len)`` without
+  timeout: the returned value can be less than the requested size, so special
+  care must be taken with this function, introduced in the Arduino
+  ``Client::`` class.  This function has also been introduced in other classes
+  not derivating from ``Client::``, e.g.  ``HardwareSerial::``.
+
+Stream extensions
+
+  Proposed Stream extensions are designed to be compatible with Arduino API,
```
Comment (earlephilhower) [inline doc/reference.rst:378]: Remove "Proposed" please.  If this merges, they'll actually  be in and not just proposed.

File: doc/reference.rst [hunk 11]
```diff
@@ -323,3 +323,193 @@ C++
...
+
+    Serial.toNow(Serial);             // serial software loopback
+
+  Beside reducing coding time, these methods optimize transfers by avoiding
+  buffer copies when possible.
+
+  - User facing API: ``Stream::to()``
+
+    The goal of streams is to transfer data between producers and consumers,
+    like the telnet/serial example above.  Four methods are proposed, all of
```
Comment (earlephilhower) [inline doc/reference.rst:403]: Same "proposed" comment.  "Added" or "extended" maybe in its place?

File: doc/reference.rst [hunk 12]
```diff
@@ -323,3 +323,193 @@ C++
...
+
+      For example, a source String will not grow during the transfer, or a
+      particular network connection supposed to send a fixed amount of data
+      before closing.  ``::toAll()`` will receive all bytes.  Timeout is
+      useful when destination needs processing time (e.g.  network or serial
+      input buffer full = please wait a bit).
+
+  - String, flash strings helpers
+
+    Two additional classes are proposed.
```
Comment (earlephilhower) [inline doc/reference.rst:438]: Ibid

File: doc/reference.rst [hunk 13]
```diff
@@ -323,3 +323,193 @@ C++
...
+    - ``StreamPtr::`` is designed to hold a constant buffer (in ram or flash).
+
+      A ``Stream::`` is made from ``const char*``, ``F("some words in
+      flash")`` or ``PROGMEM`` strings.  This class makes no copy, even with
+      data in flash.  For flash content, byte-by-byte transfers is a
+      consequence.  Other contents can be transfered at once when possible.
+
+      .. code:: cpp
+
+        StreamPtr css(F("my long css data")); // no heap/stack allocation
```
Comment (earlephilhower) [inline doc/reference.rst:449]: Suggest `//no heap/stack allocation` --> `// CSS data not copied to RAM` because the `StreamPtr` object itself will have a bit of stack for its pointers/etc., even if the data isn't dup'd.

File: doc/reference.rst [hunk 14]
```diff
@@ -323,3 +323,193 @@ C++
...
+      available data.  It is useful when source is able to tell that no more
+      data will be available for this call, or when destination is able to
+      tell that it will no more be able to receive.
+
+      For example, a source String will not grow during the transfer, or a
+      particular network connection supposed to send a fixed amount of data
+      before closing.  ``::toAll()`` will receive all bytes.  Timeout is
+      useful when destination needs processing time (e.g.  network or serial
+      input buffer full = please wait a bit).
+
```
Comment (earlephilhower) [inline doc/reference.rst:435]: This is another style/naming thing, so take it with a grain of salt, but the new method names are puzzling to me.

Instead of `Stream::toXXX` I would suggest `Stream::sendXXX` which is really what's going on (i.e. the verb, not the preopsition).
````
Stream::sendCount(dest, count); // Send count bytes to dest
Stream::sendUntilChar(dest, chr); // Send data to dest until chr matched
Stream::sendAvailable(dest); // Send all presently available data to dest
Stream::sendUntilEnd(); // Send all data to dest, even if source reads block
````

File: cores/esp8266/Stream.h [hunk 15]
```diff
@@ -102,12 +113,104 @@ class Stream: public Print {
...
+        typedef enum
+        {
+            STREAMTO_SUCCESS = 0,
+            STREAMTO_TIMED_OUT,
+            STREAMTO_READ_ERROR,
+            STREAMTO_WRITE_ERROR,
+            STREAMTO_SHORT,
+        } toReport_e;
+
+        toReport_e getLastTo () /*const*/ { return (toReport_e)getWriteError(); }
```
Comment (earlephilhower) [inline cores/esp8266/Stream.h:197]: Think this needs the work "error" in the fcn name...i.e. `getLastSendError` (see below) or `getLastToError`.

File: libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp [hunk 16]
```diff
@@ -545,111 +543,12 @@ int HTTPClient::sendRequest(const char * type, Stream * stream, size_t size)
...
-            DEBUG_HTTPCLIENT("[HTTP-Client][sendRequest] ERROR SEND PAYLOAD FAILED!");
-            return returnError(HTTPC_ERROR_SEND_PAYLOAD_FAILED);
-        } else {
-            DEBUG_HTTPCLIENT("[HTTP-Client][sendRequest] Stream payload written: %d\n", bytesWritten);
-        }
-
-    } else {
-        DEBUG_HTTPCLIENT("[HTTP-Client][sendRequest] not enough ram! need %d\n", HTTP_TCP_BUFFER_SIZE);
-        return returnError(HTTPC_ERROR_TOO_LESS_RAM);
+    // transfer all of it, with timeout
```
Comment (earlephilhower) [inline libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp:546]: Awesome code duplication reduction!  👍

File: libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp [hunk 17]
```diff
@@ -362,6 +362,19 @@ int WiFiClientSecureCtx::read(uint8_t *buf, size_t size) {
...
+const char* WiFiClientSecureCtx::peekBuffer ()
+{
+    return (const char*)_recvapp_buf;
+}
+
+// consume bytes after use (see peekBuffer)
+void WiFiClientSecureCtx::peekConsume (size_t consume)
+{
+    br_ssl_engine_recvapp_ack(_eng, consume);
+}
```
Comment (earlephilhower) [inline libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp:376]: Here I think there is aproblem.  When BSSL recvapp_ack is called, the object's recvapp_buf/len is no longer valid  (See line 353 above in the original source).  I believe you need to ack the consumed bytes and then clear the `_recvapp_buf` and `recvapp_len`.

File: tests/host/common/Arduino.cpp [hunk 18]
```diff
@@ -81,3 +81,4 @@ extern "C" void cont_yield(cont_t*)
 {
 }
 
+const char* overrideme PROGMEM = " should be overridden for better efficiency\r\n";
```
Comment (earlephilhower) [inline tests/host/common/Arduino.cpp:84]: I think you placed the char pointer in flash, but left the string in RAM.  Suggest
`const char overrideme [] PROGMEM = " should be overridden for better efficiency\r\n";`

**Review by earlephilhower — CHANGES_REQUESTED** [review]
Very nice and expansive work.  I can see the value, both in saved stack space (those 128/256b bounce buffers go away) and code size (nice reduction!!).

Couple spots I think I caught a problem, and a lot more where maybe we should figure out which of some possible ways of going forward is best.  The naming, in particular, seems odd to me but I'm only one datapoint so let's hear from others before changing anything.

File: cores/esp8266/FS.h (hunk 2 above)
Comment (TD-er) [reply cores/esp8266/FS.h:77]: program error as position is beyond the size?

File: cores/esp8266/FS.cpp [hunk 19]
```diff
@@ -66,7 +66,7 @@ int File::read() {
     return result;
 }
 
-size_t File::read(uint8_t* buf, size_t size) {
+int File::read(uint8_t* buf, size_t size) {
```
[the remark this answers is not in the document]
Comment (jandrassy) [reply cores/esp8266/FS.cpp:69]: Arduino API [Stream](https://github.com/arduino/ArduinoCore-API/blob/master/api/Stream.h) class doesn't have `read(buff, size)`. In Arduino API it is only in derived [Client](https://github.com/arduino/ArduinoCore-API/blob/master/api/Client.h) class and there the return type is int (The Client class is a mess)

[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/FS.cpp:69]: This is because of [Arduino's `Client` class](https://github.com/arduino/ArduinoCore-avr/blob/9f8d27f09f3bbd1da1374b5549a82bda55d45d44/cores/arduino/Client.h#L31L35) (this link is their current master).

This change is made necessary because in this PR I bring `int read(buffer,len)` from `Client::` to `Stream::`, and that, for the need of peekBuffer's performances.

So any class that is derived from `Stream::` and that implements `::read(buffer, len)` will have to follow Arduino's `Client::read(buffer,len)` prototype (let me call it a Fixing Change :).

Currently our `HardwareSerial` needs this change, also submoduled `SoftwareSerial` (a PR is mentioned in OP, and this PR changes the submodule link, temporarily I hope, to my own fork).
FSes need also this change because they are derived from `Stream::`.

File: cores/esp8266/Stream.h [hunk 20]
```diff
@@ -90,6 +100,7 @@ class Stream: public Print {
         }
         // terminates if length characters have been read or timeout (see setTimeout)
         // returns the number of characters placed in the buffer (0 means no valid data found)
+        // return data type: size_t
 
         size_t readBytesUntil(char terminator, char *buffer, size_t length); // as readBytes with terminator character
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/Stream.h:105]: I just added a comment here, while trying to understand the logic of their API.
I can remove it from the PR.

ref: [Arduino](https://github.com/arduino/ArduinoCore-avr/blob/9f8d27f09f3bbd1da1374b5549a82bda55d45d44/cores/arduino/Stream.h#L96L102)'s API

File: cores/esp8266/StreamDev.cpp [hunk 21]
```diff
@@ -0,0 +1,333 @@
...
+
+            if (timedOut)
+            {
+                // either (maxLen>0) nothing has been transferred for too long
+                // or readUntilChar >= 0 but char is not encountered for too long
+                // or (maxLen=0) too much time has been spent here
+                break;
+            }
+
+            if (yieldNow)
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/StreamDev.cpp:129]: Yes

File: cores/esp8266/FS.h (hunk 2 above)
Comment (d-a-v) [reply cores/esp8266/FS.h:77]: If the question is about the choice of the return type (I had the choice in this case!),
I was thinking while writing it that a signed type is better, because, and this has been discussed elsewhere in this repo not a long time ago, we can read here and there things like `if (retValue == (size_t)-1)`. Using `ssize_t` can avoid that.

Regarding the value, `someFunctionReturningASize()<0` is usually used to indicate an error, and `==0` is EOF(FS), TryAgain(non-blocking network op) or closed/timeout(blocking network op).

File: cores/esp8266/HardwareSerial.h (hunk 4 above)
Comment (d-a-v) [reply cores/esp8266/HardwareSerial.h:152]: > so I'd really use peekAvailable() as the method name in the base class...

OK

File: cores/esp8266/StreamDev.cpp (hunk 5 above)
Comment (d-a-v) [reply cores/esp8266/StreamDev.cpp:99]: The peek-buffer API is able to tell whether it is usable (data accessible and block-readable).

For example, if you get to re-read the [`in_flash` argument in `StreamPtr` constructors](https://github.com/esp8266/Arduino/pull/6979/files#diff-b7808f496813d60af97f5316fe6bdd213dcc706b86dee15da068f4015c2fa62cR164), peek-buffer API can be prevented when data are not byte-addressable (`in_flash == true`, see `::peekBufferAPI()` in this class). But the `::read()` functions are still optimized with `memcpy_P()`.
This class allows to `StreamPtr(F("I am in flash")).toAll(Serial)`.
In this case, a pointer to the source (peek-buffer API) will not be provided but the fall-back regular copy through buffer  using overloaded `::read(buffer)` will be faster thanks to `memcpy_P()`.

Note that everything is hidden to the user. A derived class knowing the peek-buffer API can take advantage of it when it says it can be used, otherwise the class will work with legacy Stream API (with possibly optimized overloaded function like above).

File: cores/esp8266/StreamDev.cpp (hunk 6 above)
Comment (d-a-v) [reply cores/esp8266/StreamDev.cpp:92]: Currently the peekBuffer API enforces byte-addressible RAM only, like Stream API.
`directbuf` is then used in `to->write()` which is `Stream::write()`.

File: cores/esp8266/StreamDev.h (hunk 7 above)
Comment (d-a-v) [reply cores/esp8266/StreamDev.h:163]: done

File: cores/esp8266/StreamDev.h [hunk 22]
```diff
@@ -0,0 +1,248 @@
...
+{
+protected:
+    const char* _buffer;
+    size_t _size;
+    bool _byteAddressible;
+    size_t _peekPointer = 0;
+
+public:
+    StreamPtr(const String& string): _buffer(string.c_str()), _size(string.length()), _byteAddressible(true) { }
+    StreamPtr(const char* buffer, size_t size): _buffer(buffer), _size(size), _byteAddressible(buffer < 0x4000000) { }
```
Comment (earlephilhower) [inline cores/esp8266/StreamDev.h:164]: Missing a 0, so off by 16x.  `_byteAddressible(buffer < 0x40000000)` everywhere here...

Comment (d-a-v) [reply cores/esp8266/StreamDev.h:164]: Sorry, I pushed too soon from the laptop without verifying.
It's a pity that these kind of constant are declared nowhere. I hate counting zeros.
Would it be into `core_esp8266_features.h` or into a new file ?
This file would be included from a `.h` included by users.

Comment (mhightower83) [reply cores/esp8266/StreamDev.h:164]: @d-a-v - Looks like the build includes _can_ find `XCHAL_INSTRAM0_VADDR` or `XCHAL_INSTRAM0_PADDR` from `core-isa.h`. `#include <sys/config.h>` appears to be an upper include that includes `#include <xtensa/config/core-isa.h>`
Or you could use `(XCHAL_DATARAM0_VADDR + XCHAL_DATARAM0_SIZE)`.  Would these serve your purpose?

File: cores/esp8266/debug.cpp (hunk 8 above)
Comment (d-a-v) [reply cores/esp8266/debug.cpp]: `iamslow()` is renamed to `__iamslow()` is declared as "C" in `debug.h` (only used by the following macro)
macro `IAMSLOW()` is left untouched and used in relevant places.

File: tests/host/common/Arduino.cpp (hunk 18 above)
Comment (d-a-v) [reply tests/host/common/Arduino.cpp]: This is a leftover, but good eyes anyway!

File: cores/esp8266/StreamDev.h (hunk 22 above)
Comment (d-a-v) [reply cores/esp8266/StreamDev.h]: @mhightower83 @earlephilhower your suggestion is in a new file `esp_priv.h` in this PR

File: cores/esp8266/StreamDev.cpp (hunk 5 above)
Comment (dok-net) [reply cores/esp8266/StreamDev.cpp:95]: @earlephilhower You may as a native speaker agree with me that `addressible` is incorrect, so please, @d-a-v, substitute `addressable` for it wherever applicable. A minor nuisance but I tripped over it :-)

Comment (d-a-v) [reply cores/esp8266/StreamDev.cpp:95]: @dok-net just re-read the last line of @earlephilhower's comment above.
Also, [this](https://en.wiktionary.org/wiki/addressible).

File: cores/esp8266/esp_priv.h [hunk 23]
```diff
@@ -0,0 +1,25 @@
+
+#ifndef __ESP_PRIV
+#define __ESP_PRIV
+
+#if defined(CORE_MOCK)
+
+constexpr bool __byteAddressible(const void* addr)
```
Comment (earlephilhower) [inline cores/esp8266/esp_priv.h:7]: See the "addressable" comment above, please.

File: tests/device/test_sw_StreamString/test_sw_StreamString.ino [hunk 24]
```diff
@@ -0,0 +1,25 @@
...
+    return true;
+}
+
+void setup ()
+{
+    Serial.begin(115200);
+    BS_RUN(Serial);
+}
+
+TEST_CASE("StreamSring tests", "[StreamString]")
```
Comment (earlephilhower) [inline tests/device/test_sw_StreamString/test_sw_StreamString.ino:22]: StreamS*t*ring typo

**Review by earlephilhower — CHANGES_REQUESTED** [review]
Very minor things on this pass.  Think we're close!

File: libraries/ESP8266WiFi/src/include/DataSource.h [hunk 25]
```diff
@@ -1,154 +0,0 @@
-/* DataSource.h - a read-only object similar to Stream, but with less methods
```
Comment (d-a-v) [inline libraries/ESP8266WiFi/src/include/DataSource.h:1]: It appeared afterwards that `Stream` integrates missing functionalities that allows itself to be a replacement for `DataSource`.

File: cores/esp8266/Stream.h [hunk 26]
```diff
@@ -102,12 +113,104 @@ class Stream: public Print {
...
+        typedef enum
+        {
+            STREAMTO_SUCCESS = 0,
+            STREAMTO_TIMED_OUT,
+            STREAMTO_READ_ERROR,
+            STREAMTO_WRITE_ERROR,
+            STREAMTO_SHORT,
+        } sendReport_e;
+
+        sendReport_e getLastSendReport () /*const*/ { return (sendReport_e)getWriteError(); }
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/Stream.h]: This is fixed by adding an enum member locally

File: doc/reference.rst [hunk 27]
```diff
@@ -326,3 +326,195 @@ C++
...
+      This method transfers all already available data to the destination.
+      There is no timeout and the returned value is 0 when there is nothing
+      to transfer or no room in the destination.
+
+    - ``Stream::toAll(dest [, timeout])``
+
+      This method waits up to the given or default timeout to transfer all
+      available data.  It is useful when source is able to tell that no more
+      data will be available for this call, or when destination is able to
+      tell that it will no more be able to receive.
```
Comment (devyte) [inline doc/reference.rst:431]: not be able to receive any more

File: cores/esp8266/StreamDev.h [hunk 28]
```diff
@@ -0,0 +1,247 @@
...
+        return 32767;
+    }
+};
+
+///////////////////////////////////////////////
+// static buffer (in flash or ram)
+// - black hole as output, swallow everything, availableForWrite = infinite
+// - Stream buffer out as input, resettable
+
+class StreamPtr: public StreamNull
```
Comment (devyte) [inline cores/esp8266/StreamDev.h:153]: Why take a String as input and not a const char * directly?
What is the difference between this and StringStream or S2Stream?
I would make the array element type a template parameter:
```cpp
template <ElementType>
class StreamArray : public StreamNull
{
...
  const ElementType * _buffer;
  StreamArray(const ElementType * array) : _buffer(array) ...
};
```
Also, maybe rename it to StreamConstPtr to emphasize that the array data can't be touched (Ptr to Const, read backwards), but I don't feel strongly about the rename, up to you.

ElementType would be a pod type or contiguous non-polymorphic struct, and must not be some complex type.
Also, cast the _buffer to uint8_t * before passing to the "normal" underlying Stream methods, and pass size * sizeof(ElementType) instead of size directly.
Also, this is likely where you want to handle arrays that are stored in flash (is that already the case in this implementation? I can't tell)

With that you should be able to stream chars, ints, doubles, simple structs, whatever.
As for String, let the StringStream implementation handle that case, including the case where you don't want to make a copy. Handling that here adds to the confusion of the String vs. Stream apocalypse.

File: cores/esp8266/StreamString.h [hunk 29]
```diff
@@ -1,39 +1,292 @@
...
+#define __STREAMSTRING_H
 
+#include "WString.h"
 
-class StreamString: public Stream, public String {
+///////////////////////////////////////////////////////////////
+// S2Stream points to a String and makes it a Stream
+// (it is also the helper for StreamString)
+
+class S2Stream: public Stream
```
Comment (devyte) [inline cores/esp8266/StreamString.h:32]: I read in the readme that this is meant to stream a String without making a copy of the string. That is not evident from the code. If that is the purpose of having this class be separate, then I suggest changing the name to reflect that, e.g.: StringViewStream or StringReferenceStream or something similar.

**Review by devyte — CHANGES_REQUESTED** [review]
I see several problems here, but overall the idea looks very good, and I see code gets unified and simpliefied.

File: cores/esp8266/Stream.h [hunk 30]
```diff
@@ -35,6 +38,12 @@
  readBytesBetween( pre_string, terminator, buffer, length)
  */
 
+// Arduino `Client: public Stream` class defines `virtual int read(uint8_t *buf, size_t size) = 0;`
+// This function is now imported into `Stream::` for `Stream::to*()`.
+// Other classes inheriting from `Stream::` and implementing `read(uint8_t *buf, size_t size)`
+// must consequently use `int` as return type, namely Hardware/SoftwareSerial, FileSystems...
+#define STREAM_READ_RETURNS_INT 1
```
[the remark this answers is not in the document]
Comment (earlephilhower) [reply cores/esp8266/Stream.h:45]: This is for compatibility with other archs, I believe.  For example, you have a lib with ESP8266 and ESP32 support and it uses Stream inheritance, you can `#ifdef` the prototype and things will "just work."

[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/Stream.h:45]: An example is the PR to espSoftwareSerial referenced in OP.

File: doc/reference.rst [hunk 31]
```diff
@@ -326,3 +326,195 @@ C++
...
+  all required bytes are received.  The ``write(buffer, length)`` (inherited
+  from ``Print::``) function is also usually blocking until the full buffer is
+  transmitted. Both functions return the number of transmitted bytes.
+
+  That's the way the Stream class works and is commonly used.
+
+  Classes derived from ``Stream::`` also usually introduce the ``read(buffer,
+  len)`` method, which is similar to ``readBytes(buffer, len)`` without
+  timeout: the returned value can be less than the requested size, so special
+  care must be taken with this function, introduced in the Arduino
```
[the remark this answers is not in the document]
Comment (jandrassy) [reply doc/reference.rst:375]: > > introduced in the Arduino Client class
> 
> what? I don't understand this. Do you mean the Arduino Client class in the official reference implementation?

yes. and SD library's File

[the remark this answers is not in the document]
Comment (devyte) [reply doc/reference.rst:375]: Ok, then I suggest making it explicit that it's in the Arduino reference.

File: cores/esp8266/FS.h (hunk 2 above)
Comment (d-a-v) [reply cores/esp8266/FS.h:77]: > into a large weird number

I'm not sure of that because `(ssize_t)((size_t)1 - (size_t)2) == -1`.
I added the cast anyway for less confusion.

File: cores/esp8266/Stream.h [hunk 32]
```diff
@@ -22,10 +22,13 @@
...
 #include <inttypes.h>
-#include "Print.h"
+#include <Print.h>
+#include <PolledTimeout.h>
+#include <sys/types.h> // ssize_t
 
-// compatability macros for testing
+// compatibility macros for testing
 /*
  #define   getInt()            parseInt()
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/Stream.h:33]: They are still in the AVR reference implementation. I suggest another PR for that.

File: cores/esp8266/Stream.h [hunk 33]
```diff
@@ -102,12 +113,104 @@ class Stream: public Print {
         virtual String readString();
         String readStringUntil(char terminator);
 
+        virtual int read (uint8_t* buffer, size_t len);
+        int read (char* buffer, size_t len) { return read((uint8_t*)buffer, len); }
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/Stream.h:119]: > Why is this not virtual?

`::read(char*,size_t)` is not in the reference implementation.
Making it virtual would add more overhead to the instances.
Having it inline and casting for user is lighter and more efficient.

File: cores/esp8266/Stream.h [hunk 34]
```diff
@@ -102,12 +113,104 @@ class Stream: public Print {
...
+        //     - and before calling peekConsume()
+        virtual const char* peekBuffer () { return nullptr; }
+
+        // consumes bytes after peekBuffer() use
+        // (then ::read() is allowed)
+        virtual void peekConsume (size_t consume) { (void)consume; }
+
+        // by default read timeout is possible (incoming data from network,serial..)
+        // children can override to false (like String::)
+        virtual bool inputTimeoutPossible () { return true; }
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/Stream.h:143]: > Why are these public?

OK to make them protected.

> I think that what you really want is to have a StreamPeekBuffer class in between that implements this api.

I don't think I want that 😆 
Given the way these classes are written, it is preferable to rely on overloading and keep the inheritance line straight. But I agree that in a template world, what you suggests would have been the preferred way.

File: cores/esp8266/Stream.h [hunk 35]
```diff
@@ -102,12 +115,106 @@ class Stream: public Print {
...
+        // ::to*() methods:
+        // - always stop before timeout when "no-more-input-possible-data"
+        //   or "no-more-output-possible-data" condition is met
+        // - always return number of transfered bytes
+        // When result is 0 or less than requested maxLen, Print::getLastSend()
+        // contains an error reason.
+
+        // transfers already buffered / immediately available data (no timeout)
+        // returns number of transfered bytes
+        size_t sendNow (Print* to) { return sendGeneric(to, -1, -1, oneShotMs::alwaysExpired); }
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/Stream.h:169]: Yes, that's the essence of this PR: `::sendBlah()` need to be *not* virtual.
Thanks to efficient helpers that are themselves depending on Stream implementation (`peekBuffer`), `::sendBlah()` are allowed to be coded in only one place and permit smaller code and easier debugging.
(I can say that in an "overload" world of course).

File: cores/esp8266/Stream.h [hunk 36]
```diff
@@ -102,12 +113,104 @@ class Stream: public Print {
...
+        // - always return number of transfered bytes
+        // When result is 0 or less than requested maxLen, this->getLastTo()
+        // contains an error reason.
+
+        // transfers already buffered / immediately available data (no timeout)
+        // returns number of transfered bytes
+        size_t sendNow (Print* to) { return sendGeneric(to, -1, -1, oneShotMs::alwaysExpired); }
+        size_t sendNow (Print& to) { return sendNow(&to); }
+
+        // transfers data until timeout
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/Stream.h:172]: > What exactly times out?

Here is the current documentation added in the PR for `::sendAll()`:

    - ``Stream::sendAll(dest [, timeout])``

      This method waits up to the given or default timeout to transfer all
      available data.  It is useful when source is able to tell that no more
      data will be available for this call, or when destination is able to
      tell that it will no more be able to receive.

      For example, a source String will not grow during the transfer, or a
      particular network connection supposed to send a fixed amount of data
      before closing.  ``::sendAll()`` will receive all bytes.  Timeout is
      useful when destination needs processing time (e.g.  network or serial
      input buffer full = please wait a bit).

I wonder whether that explanation is clear enough.

File: cores/esp8266/StreamDev.cpp [hunk 37]
```diff
@@ -0,0 +1,320 @@
...
+    parsing functions based on TextFinder library by Michael Margolis
+*/
+
+
+#include <Arduino.h>
+#include <StreamDev.h>
+
+using esp8266::polledTimeout::oneShotFastMs;
+
+size_t Stream::sendGeneric(Print* to,
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/StreamDev.cpp:28]: > Classic old school C-style nested code, which is rather hard to understand and maintain.

I don't agree with that but I will separate.

File: cores/esp8266/StreamDev.h (hunk 28 above)
Comment (d-a-v) [reply cores/esp8266/StreamDev.h:153]: > What is the difference between StreamPtr and StringStream or S2Stream?

There is no allocation in `StreamPtr::`. It's an interface that handles a ***pointer*** to make a `PROGMEM` or a `char*` directly usable as a Stream as input regardless whether data is byte readable.
The *"`Ptr`"* in its name makes it clear that the pointed object must not be modified while beeing used (speaking of `String::c_str()` as pointed object).

> StreamConstPtr

OK with this name

> Why take a String as input and not a const char * directly?

Both and others are taken. 
Taking `String` avoids users to give `myString.c_str()` as parameter which is just what we usually do for ease of reading and coding.

> template <ElementType>

There are special cases to consider. `PROGMEM`/`F()` are *not* byte-accessible. `char*` can be optimized but not when it's a `PROGMEM`.
Please check the constructors about them.

> With that you should be able to stream chars, ints, doubles, simple structs, whatever.

The purpose of this class is to make no allocation.
I guess that you are thinking of `S2Stream::`.

> Handling `String` here adds to the confusion of the String vs. Stream apocalypse

Well, it has been made clear that `String` is not and should never be a `Stream`.
Given the name `StreamConstPtr` of this class I don't think confusion will ever be made.
This class is lighter that `S2Stream::` so why not letting users use a `String` with it ?

File: cores/esp8266/StreamString.h [hunk 38]
```diff
@@ -1,39 +1,292 @@
...
+
+    virtual int read() override
+    {
+        if (peekPointer < 0)
+        {
+            // consume chars
+            if (string->length())
+            {
+                char c = string->charAt(0);
+                string->remove(0, 1);
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/StreamString.h:64]: > This looks to have the same exponential problem reported in an issue that I can't find anymore. Every char read causes the entire remaining buffer to shift => O(n^2)

This [has been answered](https://github.com/esp8266/Arduino/pull/6979#issuecomment-675182649).

By default, this class is in "consume mode". This is legacy StreamString. It means that char by char operations are O(n²). But:
- one can use it with blocks (peekBuffer API), so the string can be consumed in one operation if all its length is taken
- one can disable the consume mode (example provided using `::resetPointer(pos=0)`).
  In that case, the O(n²) issue disappears.

File: libraries/ESP8266WebServer/src/ESP8266WebServer.h [hunk 39]
```diff
@@ -164,14 +164,26 @@ class ESP8266WebServerTemplate
   void send_P(int code, PGM_P content_type, PGM_P content);
   void send_P(int code, PGM_P content_type, PGM_P content, size_t contentLength);
 
+  void send(int code, const char* content_type, Stream* stream, size_t content_length = 0);
+  void send(int code, const char* content_type, Stream& stream, size_t content_length = 0);
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply libraries/ESP8266WebServer/src/ESP8266WebServer.h:168]: > Can any object that inherits from Stream be passed in?

I guess that is the ultimate goal. Being able to use a Stream for what it's for.

> Are there cases where the byte stream would need to be url-encoded before sending?

That's on user responsibility. Raw binary is valid anyway, like in your favorite web-radio.

File: libraries/ESP8266WiFi/src/WiFiClient.cpp [hunk 40]
```diff
@@ -197,7 +197,7 @@ bool WiFiClient::getSync() const
 
 int WiFiClient::availableForWrite ()
 {
-    return _client? _client->availableForWrite(): 0;
+    return _client? (int)_client->availableForWrite(): 0;
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply libraries/ESP8266WiFi/src/WiFiClient.cpp:200]: I removed it.
`ClientContext::availableForWrite()` is `size_t` because lwIP's `snd_buf` is unsigned.

File: libraries/ESP8266WiFi/src/WiFiClient.cpp [hunk 41]
```diff
@@ -262,10 +262,14 @@ int WiFiClient::read()
...
 int WiFiClient::read(uint8_t* buf, size_t size)
 {
-    return (int) _client->read(reinterpret_cast<char*>(buf), size);
+    return (int)_client->read((char*)buf, size);
+}
+
+int WiFiClient::read(char* buf, size_t size)
+{
+    return (int)_client->read(buf, size);
 }
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply libraries/ESP8266WiFi/src/WiFiClient.cpp:273]: Let's do this in another PR (in current master it's not inline either).

File: libraries/ESP8266WiFi/src/WiFiClient.h [hunk 42]
```diff
@@ -66,7 +66,9 @@ class WiFiClient : public Client, public SList<WiFiClient> {
 
   virtual int available() override;
   virtual int read() override;
-  virtual int read(uint8_t *buf, size_t size) override;
+  virtual int read(uint8_t* buf, size_t size) override;
+  int read(char* buf, size_t size);
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply libraries/ESP8266WiFi/src/WiFiClient.h:70]: > This `::read()` looks like it should be virtual in Stream and override here

not the `char*` version.

File: libraries/esp8266/examples/StreamString/StreamString.ino [hunk 43]
```diff
@@ -0,0 +1,195 @@
+
+// this example sketch in the public domain is also a host and device test
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply libraries/esp8266/examples/StreamString/StreamString.ino:2]: > I find this rather confusing

I don't think it is wise to make a one-line example with StreamString.
Here's the current output of this example.
If you find that sources are too complex to read regarding the result, I'll move it to device tests.
```
PASSED: Test StreamConstPtr.sendAll(StreamString) (result: 'hellohellohello')
PASSED: Test StreamString<<String (result: 'hellohellohello')
PASSED: Test S2Stream.sendAll(StreamString) (result: 'hello')
PASSED: Test unmodified String given to S2Stream (result: 'hello')
PASSED: Test S2Stream.resetPointer(2): (result: 'llo')
PASSED: Test setConsume(): S2Stream().sendSize(StreamString,3) (result: 'hel')
PASSED: Test setConsume(): String given from S2Stream is swallowed (result: 'lo')
PASSED: Test StreamString(String) (result: 'lo')
PASSED: Test StreamString(char*) (result: 'hel')
PASSED: Test StreamString(char*) (result: 'abc')
PASSED: Test StreamString(F()) (result: 'abc')
PASSED: Test StreamString(int) (result: '23')
PASSED: Test StreamString(char) (result: 'a')
PASSED: Test StreamString(float) (result: '23.20')
```

File: cores/esp8266/StreamDev.cpp [hunk 44]
```diff
@@ -0,0 +1,320 @@
...
+
+            if (timedOut)
+            {
+                // either (maxLen>0) nothing has been transferred for too long
+                // or readUntilChar >= 0 but char is not encountered for too long
+                // or (maxLen=0) too much time has been spent here
+                break;
+            }
+
+            optimistic_yield(1000);
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/StreamDev.cpp:125]: > Has this been tested with a Stream that depends on SYS, e.g.: Client or whatever?

What do you think ? 😆 One of the two added example is called `WiFiEcho`. 

> Is it your expectation that the rate is limited by outputAvailableForWrite() somehow?

This function tells how much space is available for sending. If sending more, some Stream may buffer (like WiFiClient). Other would lose data or return a number of transferred bytes lower than requested. There is no rate limiting when efficiency is reached by using what's available.


> Keep in mind that the accumulation rate has to do with the code execution speed and nothing to do with actual data throughput of the receiving Stream.

I don't really get that part of your comment. I can however tell that I had very much in mind the dance with throughput and buffer space at the time of writing this function.

This function is no more than the regular transfer loop. You seem very concerned by SYS and context switching. There was a yield for large transfers which is now an optimistic yield. So "SYS Stream" like WiFiClient are triggerred often enough for the data to flow.

File: cores/esp8266/StreamString.h (hunk 29 above)
Comment (d-a-v) [reply cores/esp8266/StreamString.h:32]: > That is not evident from the code

Can you elaborate ?

> If that is the purpose of having this class be separate

The purpose is to indifferently use Strings where Streams can be used.
`StringReferenceStream` is the right meaning but is a hell of a name to type.
I'm open to other suggestions :)

File: cores/esp8266/StreamString.h [hunk 45]
```diff
@@ -1,39 +1,292 @@
...
+
+    String* string;
+    int peekPointer; // -1:String is consumed / >=0:resettable pointer
 };
 
 
-#endif /* STREAMSTRING_H_ */
+// StreamString is a S2Stream holding the String
+
+class StreamString: public String, public S2Stream
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/StreamString.h:215]: > Why use multiple inheritance like this?

A StreamString is a Stream and a String.
The functionality is brought by S2Stream which is a Stream. 

> To be explicit: is there any advantage to having these 2 classes be separate, as opposed to the current double inheritance?

S2Stream adds the possibility to use *an existing* String as a Stream.
This cannot be done by StreamString which itself holds a plain String.

File: cores/esp8266/debug.cpp [hunk 46]
```diff
@@ -22,6 +22,13 @@
 #include "debug.h"
 #include "osapi.h"
 
+#ifdef DEBUG_ESP_CORE
+void __iamslow(const char* what)
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/debug.cpp:26]: I don't agree.

File: cores/esp8266/uart.cpp [hunk 47]
```diff
@@ -240,6 +240,39 @@ uart_peek_char(uart_t* uart)
...
+    // - return already copied buffer pointer (= older data)
+    // - or return fifo when buffer is empty but then any move from fifo to
+    //   buffer should be blocked until peek_consume is called
+
+    ETS_UART_INTR_DISABLE();
+    uart_rx_copy_fifo_to_buffer_unsafe(uart);
+    ETS_UART_INTR_ENABLE();
+    if(uart->rx_buffer->wpos < uart->rx_buffer->rpos)
+        return uart->rx_buffer->size - uart->rx_buffer->rpos;
+    return uart->rx_buffer->wpos - uart->rx_buffer->rpos;
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/uart.cpp:256]: > This looks fundamentally wrong. 

- The `rpos` field is modified by user (when calling `::read()`) (*not by ISR*)
- PeekBuffer semantics insists on that "any king of `::read()`" must not be called until after the next call to `::consume()` (where `rpos` is modified but the peekBuffer discarded)
- The `wpos` field can be modified in between with the only effect that the peekBuffer length could be larger so it wouldn't interfere with the previous result given by `uart_peek_available()`.

This looks fundamentally right to me.

Counter-example appreciated.

File: cores/esp8266/uart.cpp [hunk 48]
```diff
@@ -240,6 +240,39 @@ uart_peek_char(uart_t* uart)
...
+}
+
+// return a pointer to available data buffer (size = available())
+// semantic forbids any kind of read() between peekBuffer() and peekConsume()
+const char* uart_peek_buffer (uart_t* uart)
+{
+    return (const char*)&uart->rx_buffer->buffer[uart->rx_buffer->rpos];
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/uart.cpp:263]: > so the bytes that come after the returned address aren't contiguous mem as you would expect

The size returned by `uart_peek_available()` `is contiguous`.

File: cores/esp8266/uart.h [hunk 49]
```diff
@@ -147,6 +147,16 @@ int uart_get_debug();
 void uart_start_detect_baudrate(int uart_nr);
 int uart_detect_baudrate(int uart_nr);
 
+// return number of byte accessible by peekBuffer()
+size_t uart_peek_available (uart_t* uart);
+
+// return a pointer to available data buffer (size = available())
+// semantic forbids any kind of read() before calling peekConsume()
+const char* uart_peek_buffer (uart_t* uart);
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/uart.h:155]: > These 2 functions are interrupt-unsafe

See previous replies

File: doc/reference.rst [hunk 50]
```diff
@@ -326,3 +326,195 @@ C++
...
+  Stream extensions are designed to be compatible with Arduino API, and
+  offer additional methods to make transfers more efficient and easier to
+  use.
+
+  The serial to network transfer above can be written like this:
+
+  .. code:: cpp
+
+    serverClient.toNow(Serial); // chunk by chunk
+    Serial.toNow(serverClient); // chunk by chunk
```
[the remark this answers is not in the document]
Comment (d-a-v) [reply doc/reference.rst]: `toNow()` is renamed to `sendAvailable()`

**Review by earlephilhower — APPROVED** [review]
LGTM now.  Appreciate the clearer naming!

File: cores/esp8266/Stream.h (hunk 34 above)
[the remark this answers is not in the document]
Comment (devyte) [reply cores/esp8266/Stream.h]: It is not a good idea to expose everything in a class. The private/protected keywords exist for very good reasons. You should hide implementation details whenever possible, especially in cases where methods are really internal details.
I'll ask in a different way: what would be the purpose of exposing these as public? What would be a sane use case in a sketch? I can think of use cases in objects that inherit from this, but it doesn't make sense to me to leave these open to the end user implementing a sketch.

>keep the inheritance line straight.

The line _is_ being kept straight, hierarchy is straight top to bottom. I am just suggesting to implement common functionality in a base class put in between. That is trivial to implement, and it expresses your real intent: 
- some streams are buffered, so they should inherit from StreamPeekBuffered, i.e.: Stream + peekbuffer
- some streams are not buffered, so they should inherit directly from Stream

The point here is that Streams that aren't buffered shouldn't be polluted with dummy implementations of these methods that don't apply to them.

3rd party libs that have objects that inherit from Stream won't be using these methods in their standard implementations, so they should inherit directly from Stream anyways. Unless they actually want to have implementations specific to our ESP and our peekbuffer, in which case they should inherit from out StreamPeekBuffer. From an user interface point of view, handling via a Stream base pointer is still ok for both case, as it should be.

[the remark this answers is not in the document]
Comment (d-a-v) [reply cores/esp8266/Stream.h]: I don't get it, because `Client` derives from `Stream`, some `Client` wouldn't implements these extensions while others would.
How is an hypothetical `StreamDirect` class supposed to be kept in a straight line ?
I think that would add more confusion to the API.

The peekBuffer API is in the public interface to make it accessible by users. By these functions output buffers are directly accessible without copies. Why would we want to hide it ?

**Review by devyte — APPROVED** [review]

**Comment by earlephilhower** [comment]
Congrats, @d-a-v!

**Comment by blue-wind-25** [comment]
Hello, I would like to confirm my founding. It seems that the updated ESP8266WebServer (and maybe ESP8266WiFi) relies on the non32xfer service because: 

`template <typename ServerType>`
`void ESP8266WebServerTemplate<ServerType>::send_P(int code, PGM_P content_type, PGM_P content) {`
`  StreamConstPtr ref(content, strlen_P(content));`
`  return send(code, String(content_type).c_str(), &ref);`
`}` 

-----

Then, because `PGM_P` is `const char*` then this CTOR will be called:
`StreamConstPtr(const char* buffer, size_t size)`
`: _buffer(buffer), _size(size), _byteAddressable(__byteAddressable(buffer)) { }`

which mean that the buffer will be read using non PGM method.

-----

Also, there is another CTOR:
`StreamConstPtr(const __FlashStringHelper* text)`
`: _buffer(reinterpret_cast<const char*>(text)), _size(strlen_P((PGM_P)text)), _byteAddressable(false) { }`

It casts `__FlashStringHelper` to `const char*`. While `strln_P()` is correctly called, the buffer will be read using non PGM method.

-----

Then `pgmspace.h` still defines `PSTR` as:

`#ifndef PSTRN`
`    #define PSTRN(s,n) (__extension__({static const char __pstr__[] __attribute__((__aligned__(n))) __attribute__((section( "\".irom0.pstr." __FILE__ "." __STRINGIZE(__LINE__) "."  __STRINGIZE(__COUNTER__) "\", \"aSM\", @progbits, 1 #"))) = (s); &__pstr__[0];}))`
`#endif`
`#ifndef PSTR`
`  #define PSTR(s) PSTRN(s,PSTR_ALIGN)`
`#endif`

So it seems that PSTR strings still need to be accessed using the `_P()` functions.

-----

I found that if I do not enable/include the non32xfer service then calls to web server `send_P()` will cause exception 3 (EXCCAUSE_LOAD_STORE_ERROR) inside the Arduino String class when copying the characters.

It seems also the case for SSL web server (even with non32xfer enabled, my SSL web server failed to send anything to the browser despite it does not cause exception 3). I am still unsure why this behavior with SSL happened.

I want to ask if this was by design (non32xfer must be enabled/included)?

I need to inform you that until at least the new official Arduino package is released, I will not be able to produce a test sketch because like I said to @earlephilhower in my other discussion, I do not use the Arduino build system.

Because I also follow updates from Arduino ESP8266 GIT and then modify the cores a bit to match my need and style, my application code will not compile using Arduino's original core. Therefore, I am also not sure if my comment about this is actually valid when using the original core and Arduino IDE. Thank you!

**Comment by earlephilhower** [comment]
@blue-wind-25 Can you cut-n-paste your observation into a new issue for tracking?  A closed PR can easily get overlooked.

Thx!
