### PR TITLE
Fix String::replace()

### LINKED ISSUE #5883: Some strings seem to have bogus data at the end (core 2.6.0 vs. core 2.4.2)
In ESPeasy we have some web page rendering all kinds of variables/strings as a cheat-sheet for the internal variable substitutions.
The same code built using core 2.4.2 and core 2.6.0 (both SDK 2.2.1 and SDK 2.2.2) shows different output.

Core 2.6.0:
- `%ssid%  MikroTik0�$	MikroTik0�$`
- `%sysname%  CO2_defect$	CO2_defect$`
- `{E}  €	%e2%82%ac�$`
- `&euro;  €	%e2%82%ac�$`

Core 2.4.2: 
- `%ssid%  MikroTik	MikroTik`
- `%sysname%  CO2_defect	CO2_defect`
- `{E}  €	%e2%82%ac`
- `&euro;  €	%e2%82%ac`

This is an example of a conversion which appears to be correct in both:
- `{Y}  ¥	%c2%a5`
- `&yen;  ¥	%c2%a5`

These are the ones giving different results (may be others, but these are noticeable)

These are the result from a call to this function:
```c++
void repl(const String& key, const String& val, String& s, boolean useURLencode)
{
  if (useURLencode) {
    s.replace(key, URLEncode(val.c_str()));
  } else {
    s.replace(key, val);
  }
}


const char euro[4] = {0xe2, 0x82, 0xac, 0}; // Unicode euro symbol
const char yen[3]   = {0xc2, 0xa5, 0}; // Unicode yen symbol
repl(F("{E}"), euro, s, useURLencode);
repl(F("&euro;"), euro, s, useURLencode);
repl(F("{Y}"), yen, s, useURLencode);
repl(F("&yen;"), yen, s, useURLencode);

repl(F("%ssid%"), WiFi.SSID(), s, useURLencode);
repl(F("%sysname%"), Settings.Name, s, useURLencode);
```

The ones that work just fine are the ones that were converted to a `String` object before calling this function.
The ones that fail are all char arrays, but not all of these fail like can be seen with the "yen" conversion.

It looks like the ones that fail have an odd number of characters (e.g. the example sysname is 10 characters).
These char arrays are all 0-terminated, or else they would have given issues in core 2.4.2 too.
The ones that were converted to a String before calling this `repl` function, were probably padded with more zeroes due to how the String implementation now does its allocation.

### PR DESCRIPTION
**Pull request by earlephilhower**
Fixes #5883 and supercedes #5890

The replace() function was using len() while in the middle of buffer
operations.  In SSO mode len() is not stored separately and is a call to
strlen(), which may not be legal if you're in the middle of overwriting
the SSO buffer, as was the case in ::replace when the replacement string
was longer than the find string.  This caused potential garbage at the
end of the string when accessed.  Instead, just cache the length in a
local while doing the operation.

Add in test cases from #5890 as well as some new ones that fail on the
unmodified core.

### CODE REVIEW

**Comment by earlephilhower** [comment]
Darn it.  I did run "make test" and it passed on my box before submitting.  Let me check the code once again, there may be other spots where it's iffy.

File: tests/host/core/test_string.cpp [hunk 1]
```diff
@@ -360,4 +366,65 @@ TEST_CASE("String SSO works", "[core][String]")
...
+void repl(const String& key, const String& val, String& s, boolean useURLencode)
+{
+    s.replace(key, val);
+}
+
+
+TEST_CASE("String SSO handles junk in memory", "[core][String]")
+{
+  // We fill the SSO space with garbage then construct an object in it and check consistency
+  // This is NOT how you want to use Strings outside of this testing!
```
Comment (TD-er) [inline tests/host/core/test_string.cpp]: Always nice to see your own code commented with some instruction "This is NOT how you want to use...." ;)
