### PR TITLE
UART write loop could lead to wdt with low bitrates or large buffers

### LINKED ISSUE #7746: Slow serial baudrates cause exceptions / WDT
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:			[ESP-12]
- Core Version:			[framework-arduinoespressif8266 2.7.4]
- Development Env:		[Platformio]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[WeMos D1 R2 and mini]
- Flash Mode:			[dio]
- Flash Size: 		        [4MB]
- lwip Variant:                    [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[clk]
- Flash Frequency:	        [40Mhz]
- CPU Frequency:	        [80Mhz]
- Upload Using:		        [SERIAL]
- Upload Speed:                [115200] (serial upload only)
- PlatformIO - ini file:

```cpp

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
board_build.filesystem = littlefs

; COM1 or COM3
upload_port = COM[4]
upload_speed = 115200

monitor_port = COM[4]
monitor_speed = 115200
monitor_flags=
    --parity
    N

```

### Problem Description

I want to use LittleFS to save some data coming from serial port at baudrate 110, N81
I tested the provided example in:
https://github.com/esp8266/Arduino/tree/master/libraries/LittleFS/examples/LittleFS_Timestamp
 and it works fine at baudrate 115200
but when changing baudrate to 110, the code seems to retart (exception) 

I need to have a running FS at baudrate of 110, because I can not change the baudrate of the device I am connected to.

### Sketch

```cpp

https://github.com/esp8266/Arduino/blob/master/libraries/LittleFS/examples/LittleFS_Timestamp/LittleFS_Timestamp.ino

```

### Debug Messages

@ Baudrate 110
FS with 110 baudrate

@Baudrate 115200
FS with 115200 baudrate

### PR DESCRIPTION
**Pull request by dok-net**
EspSoftwareSerial successfully uses optimistic_yield for the same purpose already.
Fixes #7746

### CODE REVIEW

**Review by d-a-v — APPROVED** [review]
LGTM !

File: cores/esp8266/uart.cpp [hunk 1]
```diff
@@ -506,8 +506,10 @@ uart_write(uart_t* uart, const char* buf, size_t size)
 
     size_t ret = size;
     const int uart_nr = uart->uart_nr;
-    while (size--)
+    while (size--) {
         uart_do_write_char(uart_nr, pgm_read_byte(buf++));
+        optimistic_yield(10000UL);
```
Comment (earlephilhower) [inline cores/esp8266/uart.cpp:511]: AIUI, `optimistic_yield` will `panic()` if not in the CONT context.  This would make any SYS-callback printouts (TCP, others) potentially crash.

@devyte, @d-a-v, any comments/ideas?  I like the idea, but the forced panic seems worse than a potential WDT...

**Review by earlephilhower — CHANGES_REQUESTED** [review]
Just worried about yield() in the UART code.  Need to be very sure it's safe and not used by SYS to log/etc...

File: cores/esp8266/uart.cpp (hunk 1 above)
Comment (devyte) [reply cores/esp8266/uart.cpp:511]: optimistic_yield() checks if it can yield (i. e. in CONT), and if enough time has elapsed since the start of the current loop. If true, it yield()s, otherwise does nothing. 

So it shouldn't panic. 

However: I seem to remember there was a change to its behavior so that yield actually only happens once every blah ms instead of after blah ms since loop start.

In any case:
- At a glance, I think the argument of 10000 is way too big, I would use something like 500, i. e. yield at most every 0.5s
- this yield won't help in the case of slow comms attempted from SYS, but you could argue that comms should be done from CONT

**Review by devyte — CHANGES_REQUESTED** [review]

File: cores/esp8266/uart.cpp (hunk 1 above)
Comment (d-a-v) [reply cores/esp8266/uart.cpp:511]: The unit is `µs` so 10k is 10ms.
It should be fine.
Maybe 1ms is better to sustain high throughput in case of a network transfer.

**Review by devyte — APPROVED** [review]
Oops, when I took a look before I saw ms. You're right, it's us. Maybe I need glasses...
One yield every 10ms should be ok. It might be worth testing if there's a difference vs 1ms before merging, but I don't see that as a stopper. 

Approving.

**Review by earlephilhower — APPROVED** [review]
Fair enough, thanks for the clarification.  LGTM!
